### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by pedroflor** [mgeeky/expdevBadChars#3]
Hey @mgeeky, great tool. Thanks!!!

Could you please give support for **python 3** ?

Thanks in advance.

**Comment by onlylonly** [comment]
I've made the conversion to python3, but i have no time to do a comprehensive testing on it yet. My preliminary testing shows that it's somewhat functioning and stable. Any testing volunteering effort would be much appreciated nonetheless. 

you may report back if you encountered any bug.

you may get the converted script from my forked branch
https://github.com/onlylonly/expdevBadChars/blob/python3/badchars.py3.py 

i will submit a PR when it's stable enough.

**Comment by pedroflor** [comment]
Thanks!

**Comment by onlylonly** [comment]
There is a issue dealing with input format "raw", if you are not using the "raw" input, there is nothing to worry about. Or else, you can get the latest commit with the bug fix for python 3.x from the forked branch.

The fix is also available for python 2.x, you may wait for @mgeeky to review the fix. Or if you need it urgently, you can get it from 
https://github.com/onlylonly/expdevBadChars/blob/origin/input-format-raw-bugfix-patch/badchars.py

**Comment by mgeeky** [comment]
Hi @onlylonly  - many thanks for submitting the Python3 version of the script! I'm gonna give it a go in few days as soon as I find a minute.

**Comment by mgeeky** [comment]
Many thanks @onlylonly for your support and work on adjusting script to become Python3 compatible. I have finally got back to this project after a longer while and merged your additions. Sorry it took so long!
